logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
spring:
  application:
    name: resolve
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false